### ISSUE TITLE
Error 500 - Internal Server Error

### ISSUE THREAD

**Issue by dknetz** [contabo/cntb#10]
Hello cntb developers

since a couple of days I get the following error when using secret-based commands. Before it worked flawlessly. Every other command works as well. I just cannot list the secrets or retrieve on of them.

I tried on different computers (native, WSL, Ubuntu 18, 20, v1.2.2, v1.2.1), but the behavior is reproducible. I already contacted the contabo support, but just got the answer to provide more data. Since it is a server error and I already use the newest version, I wanted to ask if this problem is already known or if somebody else can confirm it. Please let me know, if you need further information :-)

<img width="644" alt="image" src="https://user-images.githubusercontent.com/1337265/187744608-a7b7ec45-191a-44e9-838b-c8b1284f40e5.png">

Thanks!

**Comment by reoops** [comment]
Thank you for informing us. At least the cntb CLI tools behaves identical on all environments. We will look into it. Could you please add `--debug trace` and invoke it again. Then please only send us the X-Request-Id so that we can investigate. Thank you.

**Comment by dknetz** [comment]
Here is the x-request-id: `cee118cd-283f-40c8-925a-2a63f6fc9285`

**Comment by ngotzmann** [comment]
We have tried unsuccessfully to reproduce the behavior of the cntb. 
We are very curious what the issue is, can you please create a ticket for a directer communication.
Also, please write in the ticket that you need support of the development department and provide this github link there, then our supporter can send us the ticket directly

**Comment by dknetz** [comment]
I just wanted to write a mail to your support team. Before sending, I tried once again if cntb works without server errors. For some reasonn the problems seems to be fixed by now... I can retrieve the secret information again. Thus the problem is solved from my point of view. I didn't change anything on my machine, so I don't know why it works again. Please let me know, if you still need some other information for debugging and if I should create a ticket.

**Comment by reoops** [comment]
If it works for you we are happy. The behavior is indeed strange. Please let us know if this should occur again.
