### ISSUE TITLE
compile on MacOS  - type openapi.UpgradeInstanceRequest has no field or method AddOns

### ISSUE THREAD

**Issue by michelvankessel** [contabo/cntb#11]
When building on MacOS 12.5.1 with Go1.19 and Docker version 20.10.17, build 100c701, the `make build` process fails with the following error: 

docker container create --name dummy -v openapivolume:/openapi alpine bash
6a351b2e711788c0090a45fbf22b4578fb7564251153149f1c416e86c5eab7c7
docker cp dummy:/openapi/ .
docker rm dummy
dummy
go mod tidy
go mod download
export VERSION=$(git rev-list --tags --max-count=1 | xargs -I {} git describe --tags {}); export COMMIT=$(git rev-parse HEAD); export TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ"); go build -ldflags="-w -s -X \"contabo.com/cli/cntb/cmd.version=$VERSION\" -X \"contabo.com/cli/cntb/cmd.commit=$COMMIT\" -X \"contabo.com/cli/cntb/cmd.date=$TIMESTAMP\""
contabo.com/cli/cntb/cmd/instances
cmd/instances/upgrade.go:33:28: upgradeInstanceRequest.AddOns undefined (type openapi.UpgradeInstanceRequest has no field or method AddOns)
make: *** [build-only] Error 2

Please advice

Michel

**Comment by Maximilian-Temeschinko** [comment]
Hello michelvankessel,

i forgot to merge a breaking change to the `instance upgrade` command.
Please try to use the new release version v1.3.0 we checked it on a Darwin OS and i built successfully.

Please let us know if there are any further issues.

max

**Comment by michelvankessel** [comment]
works!

./cntb version
cntb v1.3.0

this did the trick: https://github.com/contabo/cntb/commit/ba4c4fe88f87219fd8da29b007f4991df5d95752

Michel
