### ISSUE TITLE
Brew cask

### ISSUE THREAD

**Issue by fronbasal** [contabo/cntb#14]
For macOS users a [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) would be super convenient.

**Comment by reoops** [comment]
Definitely, we will create a homebrew formulae for cntb.

**Comment by fronbasal** [comment]
Great to hear, good stuff! 🚀

**Comment by reoops** [comment]
FYI: Merge Request has been approved by homebrew team (see https://github.com/Homebrew/homebrew-core/pull/115817).

**Comment by fronbasal** [comment]
Amazing effort, thank you so much for the fast engagement ❤️ 
I am very happy about you guys' services.
