### ISSUE TITLE
Parallel make fails to build

### ISSUE THREAD

**Issue by solonovamax** [contabo/cntb#16]
Running
```
make build -j$(nproc)
```
fails due to a race condition:
- the `generate-api-clients` task deletes the `openapi` directory
- the `build-only` task requires the `openapi` directory to exist

It seems this is occurring because make is attempting to run both tasks in parallel, causing the `openapi` directory to not exist when `build-only` is run, however it always should. Running make with `-j1` solves this issue.

**Comment by reoops** [comment]
Thanks for reporting. Actually the default seems to be 1. I guess that's why we never encountered it. Seems like there is a different config on your side. 

To make sure it works we will add `MAKEFLAGS := --jobs=1` to the Makefile.
