### ISSUE TITLE
Any plans on publishing `cntb` as Docker image?

### ISSUE THREAD

**Issue by marvinruder** [contabo/cntb#17]
Currently, I am running the `cntb` CLI in a minimal Docker container based on Busybox: 

```
FROM busybox
RUN wget -qO- https://github.com/contabo/cntb/releases/download/v1.3.2/cntb_v1.3.2_Linux_x86_64.tar.gz | tar xvz -C /bin
ENTRYPOINT [ "/bin/cntb" ]
```

This works fine, but I need to update the Dockerfile and rebuild the container whenever a new version is released. It would be much better if `cntb` was officially published on [Docker Hub](https://hub.docker.com/) or a similar repository. I believe that a minimal image containing the statically compiled `cntb` binary can easily be created during your CI/CD and release process, as demonstrated in the Dockerfile above (just replace the `wget` command with `COPY …`).

**Comment by tahergalal** [comment]
There is currently no plan to perform this automatically and pushing it to docker as this is not what we had in mind for the tool so no plans currently
