### ISSUE TITLE
Checksum hash algorithm not given

### ISSUE THREAD

**Issue by erdnuesse** [contabo/cntb#18]
I found the file of checksums of 64-bit length, but I have no idea with which algo they have been generated. Thus; I am unable to verify the integrity of the archives. I use default linux cli tools, so I generally need that info to not trial and error. 
Maybe you can please provide the type of checksum that has been used.

**Comment by reoops** [comment]
Hi, we are using [goreleaser](https://goreleaser.com/) for generating and providing the releases in github.  

Regarding the checksums, please refer to <https://goreleaser.com/customization/checksum/>. We are using the default sha256 (see <https://github.com/contabo/cntb/blob/main/.goreleaser.yml>)
