### ISSUE TITLE
Does not show snapshots via cli

### ISSUE THREAD

**Issue by erdnuesse** [contabo/cntb#20]
Symptom:
Running 
~# cntb get snapshots xxxxxxxx 
shows no snapshots of the specified instance

Expected behavior: 
Running the command should return all snapshots

Logging in the web iface, I can see the snapshot.

**Comment by tahergalal** [comment]
Can you maybe open a support ticket (stating that you want it to directly to go to dev) so that we can better have information about the specific instance?

**Comment by erdnuesse** [comment]
That depends; kind of; if the issue is not reproducible and the cli seems to work with snapshots just fine on dev's end; 100% sure because then it could be a separate issue. 
If it can easily be reproduced though, I don't see the benefit in talking about one single instance if a general function seems broken. And for now I know anything about reproducibility. 
When I see a bugtracker / Issue tracker in software, and it looks like a software issue; I will use that platform. 
When I have a problem with a product in general, and I need general support, I will use that platform respectively. And with this it seemed clear to not be an issue with the product, but with the cli tool.
So I would respectfully decline opening a support ticket for now, as I might not be the only one affected and refer to general bugfixing including reproducing the issue before considering customer-specific actions. 
Thanks for your understanding.

**Comment by tahergalal** [comment]
The reason I asked for customer specific issue is because I tried to create snapshots and list snapshots and it is working. The cli (latest version) can list snapshots and can create snapshots. The problem in your case that the snapshots is not listed will need specific info to figure out and reproduce it on our side. I hope this is clear and thank you for the understanding.
