### ISSUE TITLE
System-wide shell completion for Bash

### ISSUE THREAD

**Issue by PanderMusubi** [contabo/cntb#21]
System-wide shell completion for Bash is set with

    cntb completion bash | sudo tee /etc/bash_completion.d/cntb > /dev/null

Perhaps something to add to the documentation as the command listed there does not work with `sudo`.

**Comment by tahergalal** [comment]
why do we need run cntb with sudo?

**Comment by PanderMusubi** [comment]
cntb is not needed to be run in sudo, sudo is only needed to write to /etc/bash_completion.d/cntb so all users can use the bash completion.

**Comment by tahergalal** [comment]
if you do it for all users or not this is something specific for the use case I would say
