### ISSUE TITLE
Support displayName

### ISSUE THREAD

**Issue by PanderMusubi** [contabo/cntb#25]
Please support `--displayName string` for `cntb reinstall instance --help`

See also https://api.contabo.com/#tag/Instances/operation/createInstance

**Comment by tahergalal** [comment]
The reinstall instance currently does not support setting the display name as this is basically fully reinstalling the instance. There is anther endpoint that only changes the display name 

[](https://api.contabo.com/#tag/Instances/operation/patchInstance)

for using this you can perform:  cntb update instance 12345 --displayName "VPS"
