### ISSUE TITLE
Remot upload url stroge

### ISSUE THREAD

**Issue by horasjey** [contabo/cntb#29]
hallo,
how reupload file to Object-Storages?

**Comment by tahergalal** [comment]
what do you mean? if you add the same file with the same name s3 will automatically upload it and replace the old one hope this helps

**Comment by horasjey** [comment]
> what do you mean? if you add the same file with the same name s3 will automatically upload it and replace the old one hope this helps

i mean how to upload file to objek stroges contabo

**Comment by tahergalal** [comment]
you can use the create object command.

cntb create object command check the example provided
