### ISSUE TITLE
Verbose mode for 'cntb create object'

### ISSUE THREAD

**Issue by kenorb** [contabo/cntb#36]
It would be good to add some parameter to show the progress of file being uploaded to the bucket and its transfer speed. This is especially useful for the big files. For example upload of the file failed (as per GH-37), and I've no idea at what point it failed or what's the completion progress (especially for big files which can take several days to complete).

**Comment by andreiduca03** [comment]
Added `--verbose` flag. Example:` cntb create object --storageId f2db70cc-68ce-42fa-a27c-cec87b363619 --bucket bucket123 --prefix prefix1/ --path  path1 --verbose`
