### ISSUE TITLE
希望提供一个mac窗口程序

### ISSUE THREAD

**Issue by HimekoX** [contabo/cntb#5]
希望有mac os支持

**Comment by contabo** [comment]
Could you please rephrase your texts in English please? Thanks

**Comment by HimekoX** [comment]
Hope to have mac os CLI support

**Comment by contabo** [comment]
Oh, yes of course. It is already present. Please check the releases for MacOS Apple's internal name is Darwin.

So please download either:
https://github.com/contabo/cntb/releases/download/1.1.2/cntb_1.1.2_Darwin_x86_64.tar.gz (for Intel Chips)
https://github.com/contabo/cntb/releases/download/1.1.2/cntb_1.1.2_Darwin_arm64.tar.gz (for Apple Chips like M1)

**Comment by HimekoX** [comment]
thanks alot
