### ISSUE TITLE
cntb not running on linux, give error of bad command

### ISSUE THREAD

**Issue by ikhan009** [contabo/cntb#7]
i run cntb on linux but not working. i face this issue. please guide me in details. i want to run one script to take backup and upload it on my object storage of contabo.

[root@ptp1 home]# cntb completion
-bash: cntb: command not found
[root@ptp1 home]# cntb completion bash > /etc/bash_completion.d/cntb
-bash: cntb: command not found
[root@ptp1 home]#

**Comment by stken99** [comment]
My is even better, i tried both version 

root@Linux06Docker:/home/contabo# cntb help
Command 'cntb' not found, did you mean:
  command 'cnt' from deb open-infrastructure-container-tools (20211231-1build1)
Try: apt install <deb name

**Comment by ikhan009** [comment]
i leave/stop cntb, aws cli is more user friendly. now i using aws.
first cntb command running issue, then configuration issue.
when i run configure command of cntb, give all secret , when run then giving error. that's why i stop cntb
