### ISSUE TITLE
REQ: DNS management

### ISSUE THREAD

**Issue by xxxserxxx** [contabo/cntb#9]
I'd like to be able to manage the Contabo DNS entries for my zone. This would be most useful when migrating DNS entries from another provider.

I absolutely *love* this CLI tool -- it elevated my NPS of Contabo by a couple of points for sure.

**Comment by reoops** [comment]
Great to hear. Thank you. We will step by step put all functionality into the CLI. We have to do some homework before being able to provide you with the DNS Records feature via API and CLI. It is coming.

**Comment by xxxserxxx** [comment]
I considered doing a PR for it myself, but since it requires server-side API work 🤷

Good to know it's coming; thank you!
